# Generated by Django 6.0.4 on 2026-05-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0002_user_bio_short_user_experience_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='booked_slots',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='max_capacity',
            field=models.IntegerField(),
        ),
    ]
