# Generated by Django 6.0.4 on 2026-05-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_fitnessclass_booked_slots_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitnessclass',
            name='booked_slots',
        ),
        migrations.AlterField(
            model_name='fitnessclass',
            name='max_capacity',
            field=models.PositiveIntegerField(),
        ),
    ]