# Generated by Django 6.0.4 on 2026-05-19 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0004_remove_fitnessclass_booked_slots_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('room_type', models.CharField(choices=[('GYM', 'Sala Mare'), ('GROUP', 'Sala Grup')], max_length=5)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='early_bird_discount_percent',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='early_bird_hours_before',
        ),
        migrations.RemoveField(
            model_name='fitnessclass',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='freeze_end_date',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='total_frozen_days',
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_short',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('FREE', 'Liber'), ('1TO1', 'Personal Training')], max_length=4)),
                ('start_time', models.DateTimeField()),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'INS'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pt_sessions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.room'),
        ),
    ]
