# Generated by Django 6.0.4 on 2026-05-19 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_room_remove_fitnessclass_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
