# Generated by Django 6.0.4 on 2026-06-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_gymsession_end_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='booking',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
