# Generated by Django 6.0.4 on 2026-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_alter_booking_unique_together_booking_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
    ]
# Generated by Django 6.0.4 on 2026-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_alter_booking_unique_together_booking_child_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='fitnessclass',
            name='price',
            field=models.DecimalField(decimal_places=2, default=30.0, max_digits=6),
        ),
    ]
