# Generated by Django 6.0.4 on 2026-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_fitnessclass_duration_minutes_fitnessclass_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='referral_count',
            new_name='discounts_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referral_discount_available',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
