# Generated by Django 6.0.4 on 2026-06-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0008_fitnessclass_duration_minutes_fitnessclass_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsession',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Prezent la ședință'),
        ),
    ]
