# Generated by Django 6.0.4 on 2026-06-16 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_gymsession_attended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_time',
            new_name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='child_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_early_bird',
        ),
        migrations.AlterField(
            model_name='booking',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Prezent la clasă'),
        ),
    ]
