# Generated by Django 6.0.4 on 2026-06-17 06:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0009_rename_referral_count_user_discounts_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_first_session_free_used',
        ),
        migrations.AddField(
            model_name='gymsession',
            name='is_free_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='first_free_session_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.CreateModel(
            name='SessionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_type', models.CharField(choices=[('1TO1', 'Personal Training'), ('GRP', 'Clasa de grup')], max_length=4)),
                ('duration', models.CharField(choices=[('1M', 'Lunar'), ('3M', 'Trimestrial')], max_length=3)),
                ('fitness_class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_sessions', models.PositiveIntegerField()),
                ('sessions_used', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('instructor', models.ForeignKey(blank=True, limit_choices_to={'role': 'INS'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pt_packages', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SUB', 'Abonament'), ('PKG', 'Pachet sedinte'), ('SINGLE', 'Sesiune singulara')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('description', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('session_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.sessionpackage')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='paid_by_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.sessionpackage'),
        ),
        migrations.AddField(
            model_name='gymsession',
            name='paid_by_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fitness_app.sessionpackage'),
        ),
    ]
