# Generated by Django 6.0.4 on 2026-06-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_remove_subscription_is_first_session_free_used_and_more'),
        ('fitness_app', '0011_rename_booking_date_booking_booking_time_and_more'),
    ]

    operations = [
    ]
